spring.application.name=kadoo_api
spring.datasource.url=jdbc:mysql://193.203.175.155:3306/u782216717_kadoodev
spring.datasource.username=u782216717_kadoodev
spring.datasource.password=K@d00Dev#25
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.servlet.context-path=/api